### ISSUE TITLE
Email Epic

### ISSUE THREAD

**Issue by KrashLeviathan** [hammer-io/hammer#4]
These can be broken into multiple issues across repositories:

- [ ] When a new user signs up, an email should be sent to their inbox to get confirmation before registration is complete. This prevents Bill from signing up with Steve's email address.
- [ ] When a user changes their email address on the User Settings page, two things need to happen:
  - [ ] Confirmation that the new email is valid
  - [ ] Remove the user's previous email from the Firebase Email/Password authentications and add the new email.
- [ ] Instead of an owner adding someone to a project instantly, the "Add Team Member" functionality should create an invite via the invite endpoint on the backend. Much of the backend code for this is already complete. This does two things for us: First, it prevents someone from being added as a contributor to something they don't want to contribute to. Secondly, it can be a way of inviting a collaborator who hasn't signed up for Hammer-IO yet.
- [ ] As a user, I'd like to be able to opt out of certain emails from Hammer-IO via the Email Notifications tab on the User Settings page.
- [ ] Provide functionality for admins to send emails:
  - [ ] To all users
  - [ ] To all owners and/or contributors of a given project (might want to send to the whole project team or just to the owners)
  - [ ] To a range of 1 to n users
- [ ] As a non-user, I should also be able to opt out of marketing newsletters that I'm signed up for.
