### ISSUE TITLE
Create Issue Tracker

### ISSUE THREAD

**Issue by jackcmeyer** [hammer-io/hammer#6]
The Hammer platform should have an issue tracker for better management of projects. It should include the following features: 

# The Issues
- [ ] Create, edit, delete issue
- [ ] The issue should have acceptance criteria, description, title, estimation
- [ ] An issue should have labels, and epic, and be able to be assigned to a sprint
- [ ] Assign a user(s) to the issue

# The Board
- [ ] The board should have a TODO, Doing, Done column
- [ ] The board should have a backlog
- [ ] The board should have sprints
